
package com.cl.dal.daointerface;

// auto generated imports
import com.cl.dal.dataobject.SysConfigDO;
import org.springframework.dao.DataAccessException;

/**
 * A dao interface provides methods to access database table <tt>sys_config</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/sys_config.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */

public interface SysConfigDAO {
	/**
	 *  Insert one <tt>SysConfigDO</tt> object to DB table <tt>sys_config</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into sys_config(id,background_image,carousel_figure1,carousel_figure2,carousel_figure3,carousel_figure4,carousel_figure5,raw_add_time) values (?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param sysConfig
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int insert(SysConfigDO sysConfig) throws DataAccessException;

	/**
	 *  Update DB table <tt>sys_config</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update sys_config set background_image=?, carousel_figure1=?, carousel_figure2=?, carousel_figure3=?, carousel_figure4=?, carousel_figure5=? where (id = ?)</tt>
	 *
	 *	@param sysConfig
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(SysConfigDO sysConfig) throws DataAccessException;

	/**
	 *  Query DB table <tt>sys_config</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, background_image, carousel_figure1, carousel_figure2, carousel_figure3, carousel_figure4, carousel_figure5, raw_add_time, raw_update_time from sys_config where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return SysConfigDO
	 *	@throws DataAccessException
	 */	 
    public SysConfigDO findById(int id) throws DataAccessException;

	/**
	 *  Query DB table <tt>sys_config</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, background_image, carousel_figure1, carousel_figure2, carousel_figure3, carousel_figure4, carousel_figure5, raw_add_time, raw_update_time from sys_config order by id DESC</tt>
	 *
	 *	@return SysConfigDO
	 *	@throws DataAccessException
	 */	 
    public SysConfigDO findOne() throws DataAccessException;

	/**
	 *  Delete records from DB table <tt>sys_config</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from sys_config where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int deleteById(int id) throws DataAccessException;

}