
package com.cl.dal.dataobject;

import java.io.Serializable;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

// auto generated imports
import java.util.Date;

/**
 * A data object class directly models database table <tt>sys_config</tt>.
 *
 * This file is generated by <tt>specialmer-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/sys_config.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>specialmer-dalgen</tt> 
 * to generate this file.
 *
 * @author peigen
 */
public class SysConfigDO implements Serializable{
	/** Comment for <code>serialVersionUID</code> */
    private static final long serialVersionUID = -4282603875229233564L;

    //========== properties ==========

	private int id;

	private String backgroundImage;

	private String carouselFigure1;

	private String carouselFigure2;

	private String carouselFigure3;

	private String carouselFigure4;

	private String carouselFigure5;

	private Date rawAddTime;

	private Date rawUpdateTime;

    //========== getters and setters ==========

	public int getId() {
		return id;
	}
	
	public void setId(int id) {
		this.id = id;
	}

	public String getBackgroundImage() {
		return backgroundImage;
	}
	
	public void setBackgroundImage(String backgroundImage) {
		this.backgroundImage = backgroundImage;
	}

	public String getCarouselFigure1() {
		return carouselFigure1;
	}
	
	public void setCarouselFigure1(String carouselFigure1) {
		this.carouselFigure1 = carouselFigure1;
	}

	public String getCarouselFigure2() {
		return carouselFigure2;
	}
	
	public void setCarouselFigure2(String carouselFigure2) {
		this.carouselFigure2 = carouselFigure2;
	}

	public String getCarouselFigure3() {
		return carouselFigure3;
	}
	
	public void setCarouselFigure3(String carouselFigure3) {
		this.carouselFigure3 = carouselFigure3;
	}

	public String getCarouselFigure4() {
		return carouselFigure4;
	}
	
	public void setCarouselFigure4(String carouselFigure4) {
		this.carouselFigure4 = carouselFigure4;
	}

	public String getCarouselFigure5() {
		return carouselFigure5;
	}
	
	public void setCarouselFigure5(String carouselFigure5) {
		this.carouselFigure5 = carouselFigure5;
	}

	public Date getRawAddTime() {
		return rawAddTime;
	}
	
	public void setRawAddTime(Date rawAddTime) {
		this.rawAddTime = rawAddTime;
	}

	public Date getRawUpdateTime() {
		return rawUpdateTime;
	}
	
	public void setRawUpdateTime(Date rawUpdateTime) {
		this.rawUpdateTime = rawUpdateTime;
	}


	/**
     * @return
     *
     * @see java.lang.Object#toString()
     */
	@Override
    public String toString() {

        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}
