--商品表  add by liugy  2017-3-26
CREATE TABLE `clh_product` (
  `product_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `supplier_id` bigint(20) NOT NULL COMMENT '供应商id',
  `supplier_name` varchar(100) DEFAULT NULL COMMENT '供应商名称',
  `product_name` varchar(100) NOT NULL COMMENT '产品名称',
  `product_number` varchar(200) NOT NULL COMMENT '产品编号',
  `product_status` varchar(30) NOT NULL COMMENT '产品状态/on/off/del',
  `product_unit` varchar(30) NOT NULL COMMENT '计量单位',
  `price1` bigint(20) DEFAULT NULL,
  `price1_range` varchar(200) DEFAULT NULL,
  `price2` bigint(20) DEFAULT NULL,
  `price2_range` varchar(200) DEFAULT NULL,
  `price3` bigint(20) DEFAULT NULL,
  `price3_range` varchar(200) DEFAULT NULL,
  `product_type` varchar(100) DEFAULT NULL COMMENT '产品类型',
  `start_order_count` bigint(20) DEFAULT NULL COMMENT '起订量',
  `product_detail` text COMMENT '商品详情',
  `product_start_date` date DEFAULT NULL COMMENT '产品发布日期',
  `product_modify_date` date DEFAULT NULL COMMENT '产品修改日期',
  `product_delete_date` date DEFAULT NULL COMMENT '产品删除日期',
  `ip_address` varchar(100) DEFAULT NULL,
  `facade` varchar(20) DEFAULT NULL COMMENT '退款类型（随时可退，过期可退..)',
  `last_view_time` date DEFAULT NULL COMMENT '最近点击时间',
  `view_count` bigint(20) NOT NULL DEFAULT '0' COMMENT '点击量',
  `small_pic_path` varchar(300) DEFAULT NULL COMMENT '小图',
  `big_pic_path` varchar(300) DEFAULT NULL COMMENT '大图',
  `middle_pic_path` varchar(300) DEFAULT NULL COMMENT '微信端展示图片',
  `small_pic_path1` varchar(300) DEFAULT NULL,
  `big_pic_path1` varchar(300) DEFAULT NULL,
  `middle_pic_path1` varchar(300) DEFAULT NULL COMMENT '微信端展示图片',
  `small_pic_path2` varchar(300) DEFAULT NULL,
  `big_pic_path2` varchar(300) DEFAULT NULL,
  `middle_pic_path2` varchar(300) DEFAULT NULL COMMENT '微信端展示图片',
  `small_pic_path3` varchar(300) DEFAULT NULL,
  `big_pic_path3` varchar(300) DEFAULT NULL,
  `middle_pic_path3` varchar(300) DEFAULT NULL COMMENT '微信端展示图片',
  `post_type` varchar(20) DEFAULT NULL COMMENT '运费类型',
  `market_price` bigint(20) DEFAULT NULL COMMENT '市场价格',
  `product_style` varchar(30) DEFAULT NULL COMMENT '产品款式',
  `pt_tag` varchar(200) DEFAULT NULL COMMENT '商品标签',
  `pt_keyWords` varchar(200) DEFAULT NULL COMMENT '商品关键词',
  `cost_price` bigint(20) DEFAULT NULL COMMENT '成本价',
  `weight` double(20,0) DEFAULT NULL COMMENT '商品重量',
  `materail` varchar(100) DEFAULT NULL COMMENT '商品材料',
  `avgscore` float DEFAULT '0' COMMENT '评价平均分',
  `raw_add_time` timestamp NULL DEFAULT '0000-00-00 00:00:00',
  `raw_update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`product_id`),
  KEY `product_supplier_id` (`supplier_id`) USING BTREE,
  KEY `product_product_type` (`product_type`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=373 DEFAULT CHARSET=utf8;

-- 系统设置
CREATE TABLE `sys_config` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `background_image` varchar(200) DEFAULT NULL COMMENT '登录页背景图',
  `carousel_figure1` varchar(200) DEFAULT NULL COMMENT '主页轮播1',
  `carousel_figure2` varchar(200) DEFAULT NULL COMMENT '主页轮播2',
  `carousel_figure3` varchar(200) DEFAULT NULL COMMENT '主页轮播3',
  `carousel_figure4` varchar(200) DEFAULT NULL COMMENT '主页轮播4',
  `carousel_figure5` varchar(200) DEFAULT NULL COMMENT '主页轮播5',
  `raw_add_time` timestamp NULL DEFAULT NULL COMMENT '新增时间',
  `raw_update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='系统配置'
